services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./setup/db_files/:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: postgres
    expose:
      - "5432"
    networks:
      - ziwg
  backend:
    restart:
      unless-stopped
    build:
        context: ..
        dockerfile: /docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db
    networks:
        - ziwg

networks:
    ziwg:
        driver: bridge